name = "rdap"
account_id = "f5686db3c4f5b3e38b8f15b0561a28a8"
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]

main = "src/index.ts"
routes = [{ pattern = "rdap.mirio.dev", custom_domain = true }]

[[kv_namespaces]]
id = "2fbd241b8f2349e5993d39a2208be142"
binding = "UPSTREAM"

[observability]
enabled = true
head_sampling_rate = 1

[env.production]
name = "rdap"
workers_dev = false

[env.production.observability]
enabled = true
head_sampling_rate = 1
